baseURL: "https://zh2k3ang.github.io/"
title: 丘山
# paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

# minify:
    # disableXML: true
    # minifyOutput: true
    
menu:
    main:
        - identifier: archives
          name: 所有
          url: /archives/
          weight: 1
        #- identifier: categories
        #  name: 分类
        #  url: /categories/
        #  weight: 2
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 2
        - identifier: About me
          name: 作者
          url: /about
          weight: 3
        

          
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: 丘山
    description: "我们生在同一个世界，却活在不同的世界"
    author: 康康

    ShowReadingTime: true
    ShowShareButtons: false
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false

    label:
        text: "首页"

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: 我们生在同一个世界，却活在不同的世界
        subtitle: welcome to my world
        buttons:
            - name: 致知
              url: categories/article
            - name: 咏志
              url: categories/poetry
            - name: 求索
              url: categories/note